import { useApp } from "../../store/appStore";

/** AI-feature strings kept local to the feature so this work does not collide
 *  with edits to the shared i18n.ts. */
const zhCN = {
    title: "AI 助手",
    subtitle: "自然语言写 SQL · 本地模型 · 不出机",
    settings: "AI 设置",
    provider: "推理来源",
    providerBuiltin: "内置模型",
    providerLocal: "本地服务",
    providerCloud: "云端 API",
    builtinNotReady: "内置模型尚未安装。可先切换到「本地端点」或「云端 API」，或稍后一键下载内置模型。",
    baseUrl: "接口地址",
    apiKey: "API Key",
    model: "模型",
    includeSample: "把真实取值和样本行发给 AI（默认关）",
    includeSampleHint: "关掉后仍会发送：指标名、维度名、行数、以及分析结论本身（结论里会出现真实的网点/大区名称和数值）。打开后额外发送：每个维度最多 8 个真实取值、结果的前 3 行。",
    placeholder: "用中文描述你想查什么，例如：统计每个网点本月线下销售额，按额度降序…",
    send: "发送",
    stop: "停止",
    clear: "清空对话",
    insertToEditor: "插入编辑器",
    copy: "复制",
    copied: "已复制",
    thinking: "生成中…",
    modeThinking: "思考",
    modeDirect: "非思考",
    modeThinkingTitle: "思考模式：模型会先推理再回答；点击切换为非思考",
    modeDirectTitle: "非思考模式（默认）：模型直接回答；点击开启思考",
    ex1: "这个库里都有哪些表?",
    ex2: "查某张表的前 20 行看看",
    ex3: "按某个字段分组统计数量",
    noConnection: "请先在左侧连接一个数据库，AI 才能看到库表结构。",
    schemaHint: "已把 {tables} 张相关表的结构作为上下文",
    empty: "问我任何关于当前库的查询。生成的 SQL 只会放进编辑器，绝不自动执行。",
    errorPrefix: "AI 调用失败：",
    cannotReach: "连不上推理服务（{url}）。检查该来源是否在运行，或到设置里切换来源。",
    demoNote: "（演示占位：内置模型还没装，这是本地生成的示例，仅供预览 UI）",
    close: "关闭",
    save: "保存",
    runSelection: "执行选中 SQL",
    askAi: "问 AI…",
    inlineReview: "检查",
    inlineOptimize: "优化",
    inlineFormat: "规范",
    inlineExplain: "解释",
    inlineFromComment: "按注释写 SQL",
    inlineAsk: "问 AI，或让它按注释/需求写 SQL…",
    replaceSel: "替换选中",
    insertCaret: "插入",
    runReadonly: "运行(只读)",
    back: "换个动作",
    writeBlocked: "AI 只支持只读查询，已拦截其中的写操作。",
    selectionHint: "已选中 {n} 字",
    wholeDoc: "整段",
    engineDesktopOnly: "内置引擎需在桌面版(Tauri)中运行;网页预览下请用「本地端点」或「云端 API」。",
    engineBinaryMissing: "未找到 llama-server。请安装 llama.cpp(brew install llama.cpp),或把二进制放到 ~/.db-sonde/bin/。",
    engineModelMissing: "未找到模型。把 GGUF 放到 ~/.db-sonde/models/(推荐 Qwen2.5-Coder-7B-Q4_K_M)。",
    engineModelFound: "模型:{name}({size})",
    engineStart: "启动内置引擎",
    engineStarting: "正在启动(加载模型可能要十几秒)…",
    engineReady: "内置引擎已就绪 · {url}",
    engineStop: "停止",
    engineStartFailed: "启动失败:{err}",
    modelDownload: "一键下载内置模型 (Qwen2.5-Coder-7B · 约 4.7GB)",
    modelDownloading: "下载中… {pct}%（{done}/{total}）",
    modelDownloadFailed: "下载失败:{err}。可重试(支持断点续传)或手动放入 ~/.db-sonde/models/。",
    modelDownloadDone: "模型已下载,可以启动内置引擎了。",
};

/* en 用 Record<keyof typeof zhCN, string> 约束 —— 少一个键直接编译不过。
   共享的 i18n.ts 本来就是这么约的,这儿漏了:AI 面板的文案只加中文、不加英文时
   没人拦得住,而切到英文界面上会直接显示原始键名(「modelDownloadFailed」这种),
   只有用英文的人才看得见。用类型堵住比写测试彻底 —— 改错当场编译失败。 */
const en: Record<keyof typeof zhCN, string> = {
    title: "AI Assistant",
    subtitle: "NL→SQL · local model · stays on-device",
    settings: "AI settings",
    provider: "Inference source",
    providerBuiltin: "Built-in model",
    providerLocal: "Local service",
    providerCloud: "Cloud API",
    builtinNotReady: "The built-in model isn't installed yet. Switch to Local or Cloud for now, or download it later.",
    baseUrl: "Base URL",
    apiKey: "API Key",
    model: "Model",
    includeSample: "Send real values and sample rows to the AI (off by default)",
    includeSampleHint: "Still sent when off: metric and dimension names, row counts, and the analysis itself (conclusions name real stores/regions and numbers). Sent additionally when on: up to 8 real values per dimension and the first 3 result rows.",
    placeholder: "Describe what you want to query in plain language…",
    send: "Send",
    stop: "Stop",
    clear: "Clear chat",
    insertToEditor: "Insert into editor",
    copy: "Copy",
    copied: "Copied",
    thinking: "Generating…",
    modeThinking: "Thinking",
    modeDirect: "Direct",
    modeThinkingTitle: "Thinking mode: reason before answering; click for direct mode",
    modeDirectTitle: "Direct mode (default): answer without reasoning; click to enable thinking",
    ex1: "What tables are in this database?",
    ex2: "Show the first 20 rows of a table",
    ex3: "Count rows grouped by a column",
    noConnection: "Connect a database on the left first, so the AI can see the schema.",
    schemaHint: "Using {tables} related table(s) as context",
    empty: "Ask anything about the current database. Generated SQL only goes into the editor — never auto-run.",
    errorPrefix: "AI request failed: ",
    cannotReach: "Can't reach the inference service ({url}). Check it's running or switch the source in settings.",
    demoNote: "(placeholder: built-in model not installed — this is a local sample for UI preview)",
    close: "Close",
    save: "Save",
    runSelection: "Run selected SQL",
    askAi: "Ask AI…",
    inlineReview: "Review",
    inlineOptimize: "Optimize",
    inlineFormat: "Format",
    inlineExplain: "Explain",
    inlineFromComment: "Comment → SQL",
    inlineAsk: "Ask AI, or turn a comment/requirement into SQL…",
    replaceSel: "Replace",
    insertCaret: "Insert",
    runReadonly: "Run (read-only)",
    back: "Back",
    writeBlocked: "AI only produces read-only queries — a write was blocked.",
    selectionHint: "{n} chars selected",
    wholeDoc: "whole editor",
    engineDesktopOnly: "The built-in engine runs in the desktop (Tauri) build; in the web preview use Local or Cloud.",
    engineBinaryMissing: "llama-server not found. Install llama.cpp (brew install llama.cpp) or place the binary in ~/.db-sonde/bin/.",
    engineModelMissing: "No model found. Put a GGUF in ~/.db-sonde/models/ (recommended: Qwen2.5-Coder-7B-Q4_K_M).",
    engineModelFound: "Model: {name} ({size})",
    engineStart: "Start built-in engine",
    engineStarting: "Starting (loading the model can take ~10s)…",
    engineReady: "Built-in engine ready · {url}",
    engineStop: "Stop",
    engineStartFailed: "Start failed: {err}",
    modelDownload: "Download built-in model (Qwen2.5-Coder-7B · ~4.7GB)",
    modelDownloading: "Downloading… {pct}% ({done}/{total})",
    modelDownloadFailed: "Download failed: {err}. Retry (resumable) or place it manually in ~/.db-sonde/models/.",
    modelDownloadDone: "Model downloaded — you can start the built-in engine now.",
};

const S = { "zh-CN": zhCN, en };

export type AiStringKey = keyof typeof zhCN;

export function useAiStrings() {
  const language = useApp((s) => s.language);
  const table = S[language] ?? S.en;
  return (key: AiStringKey, vars?: Record<string, string | number>) => {
    let text: string = table[key];
    if (vars) for (const [k, v] of Object.entries(vars)) text = text.replace(`{${k}}`, String(v));
    return text;
  };
}
